name: fishdetection_tilapia
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.1
  camera_web: ^0.3.5
  image_picker: ^0.8.7
  image_picker_for_web: ^2.0.0 # Optional for web-based image picker
  path_provider: ^2.0.11
  file_picker: ^5.0.0
  permission_handler: ^10.2.0 # Added the permission_handler dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
